### ISSUE TITLE
table_ref would include also subselects, aliases, etc. but NORMALIZE/ALIGN does not

### ISSUE THREAD

**Issue by Piiit** [Piiit/tpg#13]
Should we fix this or just give a explanatory error message

**FIX IT**

**Comment by Piiit** [comment]
Test things also for sub-queries and aliases

**Comment by Piiit** [comment]
The first two commands work, whereas the third does not...

```
select * from (r align r r2 on true with (ts,te,ts,te))x;
select * from (r align r r2 on r.a=r2.a with (ts,te,ts,te))x;
select * from ( (select * from r where a='j') r align r r2 on r.a=r2.a with (ts,te,ts,te))x;
```

**Comment by Piiit** [comment]
**This part is solved!**

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fb30567caea in strlen () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007fb30567caea in strlen () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000797892 in MemoryContextStrdup (context=0x1143030, string=string@entry=0x0) at mcxt.c:1070
#2  0x00000000007978cf in pstrdup (in=in@entry=0x0) at mcxt.c:1082
#3  0x00000000005ecc0c in makeAlias (aliasname=0x0, colnames=colnames@entry=0x0) at makefuncs.c:413
#4  0x0000000000523ed6 in makeTemporalQuerySkeleton (nameRN=nameRN@entry=0x11b2340 "*RN*", nameP1=nameP1@entry=0x11b2358 "*P1*", 
    j=<optimized out>) at parse_clause.c:220
#5  0x0000000000525512 in transformTemporalAlign (pstate=0x11b2120, j=0x11b1de8) at parse_clause.c:318
#6  transformFromClauseItem (pstate=pstate@entry=0x11b2120, n=0x11b1de8, top_rte=top_rte@entry=0x7ffe98b686e0, 
    top_rti=top_rti@entry=0x7ffe98b686dc, namespace=namespace@entry=0x7ffe98b686e8) at parse_clause.c:1542
#7  0x00000000005266d3 in transformFromClause (pstate=pstate@entry=0x11b2120, frmList=<optimized out>) at parse_clause.c:689
#8  0x000000000050844c in transformSelectStmt (stmt=0x11b1fc0, pstate=0x11b2120) at analyze.c:1041
#9  transformStmt (pstate=0x11b2120, parseTree=0x11b1fc0) at analyze.c:247
#10 0x0000000000509cdd in parse_analyze (parseTree=0x11b1fc0, 
    sourceText=0x11b06e0 "select * from ( (select * from r where a='j') r align r r2 on r.a=r2.a with (ts,te,ts,te))x;", 
    paramTypes=0x0, numParams=0) at analyze.c:104
#11 0x0000000000695d73 in pg_analyze_and_rewrite (parsetree=parsetree@entry=0x11b1fc0, 
    query_string=query_string@entry=0x11b06e0 "select * from ( (select * from r where a='j') r align r r2 on r.a=r2.a with (ts,te,ts,te))x;", paramTypes=paramTypes@entry=0x0, numParams=numParams@entry=0) at postgres.c:669
#12 0x0000000000697f23 in exec_simple_query (
    query_string=0x11b06e0 "select * from ( (select * from r where a='j') r align r r2 on r.a=r2.a with (ts,te,ts,te))x;")
    at postgres.c:1030
#13 PostgresMain (argc=<optimized out>, argv=argv@entry=0x1144c48, dbname=0x1144b00 "A", username=<optimized out>)
    at postgres.c:4040
#14 0x000000000046541d in BackendRun (port=0x1164d20) at postmaster.c:4230
#15 BackendStartup (port=0x1164d20) at postmaster.c:3906
#16 ServerLoop () at postmaster.c:1665
#17 0x0000000000645b66 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x1142d50) at postmaster.c:1274
#18 0x0000000000465e8e in main (argc=3, argv=0x1142d50) at main.c:223

```

**Comment by Piiit** [comment]
```
SET log_error_verbosity = verbose;
drop table if exists r;
create table r(a char, ts int, te int);
insert into r values
('a',1,8), 
('j',2,6), 
('a',8,12);
select * from r where a='j';
 a | ts | te 
---+----+----
 j |  2 |  6
(1 row)

select * from (r align r r2 on true with (ts,te,ts,te))x;
 a | ts | te 
---+----+----
 a |  1 |  8
 a |  2 |  6
 j |  2 |  6
 a |  8 | 12
(4 rows)

select * from (r align r r2 on r.a=r2.a with (ts,te,ts,te))x;
 a | ts | te 
---+----+----
 a |  1 |  8
 j |  2 |  6
 a |  8 | 12
(3 rows)

select * from ( (select * from r where a='j') r align r r2 on true with (ts,te,ts,te))x;
 a | ts | te 
---+----+----
 j |  2 |  6
(1 row)

select * from r where a='j';
 a | ts | te 
---+----+----
 j |  2 |  6
(1 row)

select * from r where ts <= 1;
 a | ts | te 
---+----+----
 a |  1 |  8
(1 row)

select * from ( (select * from r where a='j') r align (select * from r where ts <= 1) r2 on true with (ts,te,ts,te))x;
 a | ts | te 
---+----+----
 j |  2 |  6
(1 row)

$ pw_pgcontrol.sh psql A
psql (9.6devel)
Type "help" for help.

A=# select * from ( (select * from r where a='j') rx normalize r on true with (ts,te,ts,te))x;
 a | ts | te 
---+----+----
 j |  2 |  6
(1 row)

A=# select * from ( (select * from r where a='j') r align (select * from r where ts <= 1) r2 on true with (ts,te,ts,te))x;
 a | ts | te 
---+----+----
 j |  2 |  6
(1 row)

A=# select * from ( (select * from r where a='j') r normalize (select * from r where ts <= 1) r2 on true with (ts,te,ts,te))x;
 a | ts | te 
---+----+----
 j |  2 |  6
(1 row)

A=# explain select * from ( (select * from r where a='j') r normalize (select * from r where ts <= 1) r2 on true with (ts,te,ts,te))x; 
                                               QUERY PLAN                                               
--------------------------------------------------------------------------------------------------------
 Subquery Scan on x  (cost=372.72..431.33 rows=2468 width=16)
   ->  Adjustment(for NORMALIZE)  (cost=372.72..406.65 rows=2468 width=28)
         ->  Sort  (cost=372.72..375.80 rows=1234 width=28)
               Sort Key: (row_number() OVER (?)), "*SELECT* 1"."*P1*"
               ->  Nested Loop Left Join  (cost=0.00..309.36 rows=1234 width=28)
                     Join Filter: (("*SELECT* 1"."*P1*" >= r.ts) AND ("*SELECT* 1"."*P1*" < r.te))
                     ->  WindowAgg  (cost=0.00..33.24 rows=9 width=16)
                           ->  Seq Scan on r  (cost=0.00..33.12 rows=9 width=16)
                                 Filter: (a = 'j'::bpchar)
                     ->  Materialize  (cost=0.00..84.76 rows=1234 width=4)
                           ->  Append  (cost=0.00..78.59 rows=1234 width=4)
                                 ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..39.30 rows=617 width=4)
                                       ->  Seq Scan on r r_1  (cost=0.00..33.12 rows=617 width=4)
                                             Filter: (ts <= 1)
                                 ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..39.30 rows=617 width=4)
                                       ->  Seq Scan on r r_2  (cost=0.00..33.12 rows=617 width=4)
                                             Filter: (ts <= 1)
(17 rows)

A=# \i unibz/manualtests/normalize-subquery-std.sql 
SET
 row_number | a | ts | te | a | ts | te | p1 
------------+---+----+----+---+----+----+----
          1 | j |  2 |  6 |   |    |    |   
(1 row)

A=# \i unibz/manualtests/align-subquery-std.sql 
SET
 row_number | a | ts | te | p1 | p2 
------------+---+----+----+----+----
          1 | j |  2 |  6 |  2 |  6
(1 row)

A=# explain select * from ( (select * from r where a='j') r normalize (select * from r where ts <= 1) r2 on true with (ts,te,ts,te))x;
                                               QUERY PLAN                                               
--------------------------------------------------------------------------------------------------------
 Subquery Scan on x  (cost=372.72..431.33 rows=2468 width=16)
   ->  Adjustment(for NORMALIZE)  (cost=372.72..406.65 rows=2468 width=28)
         ->  Sort  (cost=372.72..375.80 rows=1234 width=28)
               Sort Key: (row_number() OVER (?)), "*SELECT* 1"."*P1*"
               ->  Nested Loop Left Join  (cost=0.00..309.36 rows=1234 width=28)
                     Join Filter: (("*SELECT* 1"."*P1*" >= r.ts) AND ("*SELECT* 1"."*P1*" < r.te))
                     ->  WindowAgg  (cost=0.00..33.24 rows=9 width=16)
                           ->  Seq Scan on r  (cost=0.00..33.12 rows=9 width=16)
                                 Filter: (a = 'j'::bpchar)
                     ->  Materialize  (cost=0.00..84.76 rows=1234 width=4)
                           ->  Append  (cost=0.00..78.59 rows=1234 width=4)
                                 ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..39.30 rows=617 width=4)
                                       ->  Seq Scan on r r_1  (cost=0.00..33.12 rows=617 width=4)
                                             Filter: (ts <= 1)
                                 ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..39.30 rows=617 width=4)
                                       ->  Seq Scan on r r_2  (cost=0.00..33.12 rows=617 width=4)
                                             Filter: (ts <= 1)
(17 rows)

A=# select * from ( (select * from r where a='j') r align (select * from r where ts <= 1) r2 on true with (ts,te,ts,te))x; a | ts | te 
---+----+----
 j |  2 |  6
(1 row)

A=# 
```
